version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=projects_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - NEXT_PUBLIC_BASE_URL=http://localhost:8080
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=projects_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/db/init/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

volumes:
  postgres_data: 